name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
    - uses: actions/checkout@v1

    - name: install packages
      run: |
        sudo apt-get update         
        sudo apt-get install -y     \
          xorg-dev                  \
          libglu1-mesa-dev          \
          xpra                      \
          xserver-xorg-video-dummy  \
          freeglut3-dev             

    - name: configure
      run: cmake  -S. --preset=main-github

    - name: build
      run: cmake --build ./build

    - name: run test
      run: ./build/test/polyscope-test --gtest_catch_exceptions=0 backend=openGL_mock
  
  build_shared:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
    - uses: actions/checkout@v1

    - name: install packages
      run: |
        sudo apt-get update          
        sudo apt-get install -y     \
          xorg-dev                  \
          libglu1-mesa-dev          \
          xpra                      \
          xserver-xorg-video-dummy  \
          freeglut3-dev             

    - name: configure
      run: cmake  -S. --preset=main-github

    - name: build
      run: cmake --build ./build

    - name: run test
      run: ./build/test/polyscope-test --gtest_catch_exceptions=0 backend=openGL_mock
