name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  VCPKG_ROOT: /usr/local/share/vcpkg

jobs:
  build:
    runs-on: macos-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
    - uses: actions/checkout@v1

    - name: setup
      run: git -C $VCPKG_ROOT reset --hard  && git -C $VCPKG_ROOT pull

    - name: configure
      run: cmake  -S. --preset=main-github -DCMAKE_C_COMPILER=$(which cc) -DCMAKE_CXX_COMPILER=$(which c++) -DCMAKE_MAKE_PROGRAM=$(which make)

    - name: build
      run: cmake --build ./build

    - name: run test
      run: ./build/test/polyscope-test --gtest_catch_exceptions=0 backend=openGL_mock

  build_shared:
    runs-on: macos-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
    - uses: actions/checkout@v1

    - name: setup
      run: git -C $VCPKG_ROOT reset --hard  && git -C $VCPKG_ROOT pull

    - name: configure
      run: cmake  -S. --preset=main-github -DBUILD_SHARED_LIBS=on -DCMAKE_C_COMPILER=$(which cc) -DCMAKE_CXX_COMPILER=$(which c++) -DCMAKE_MAKE_PROGRAM=$(which make)

    - name: build
      run: cmake --build ./build

    - name: run test
      run: ./build/test/polyscope-test --gtest_catch_exceptions=0 backend=openGL_mock
