name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  VCPKG_ROOT: C:\vcpkg    

jobs:
  build:
    runs-on: windows-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
    - uses: actions/checkout@v1

    - name: setup
      run: git -C $env:VCPKG_ROOT pull

    - name: configure
      run: cmake  -S. --preset=main-github

    - name: build
      run: cmake --build ./build

    - name: run test
      run: ./build/test/polyscope-test --gtest_catch_exceptions=0 backend=openGL_mock
